/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Hp' at '24/10/20 5:46 PM' with Gradle 3.0
 *
 * @author Hp, @date 24/10/20 5:46 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
